### ISSUE TITLE
Timeline to upload the remaining sequences

### ISSUE THREAD

**Issue by FengQiaojun** [chentianyangWHU/WHUVID#1]
Thank you for making this dataset public! It will be super helpful for the VIO and SLAM research!
I wonder whether you have a timeline to upload the remaining sequences? In the README it is mentioned that 
> The uploading work is expected to be completed within two week (from April 19, 2022). 

It has been 2 weeks since then but only 5 seqs are available now.
Also, is it possible to also provide copies on Google Drive for a broader accessibility :)
Thank you

**Comment by SleepEarlyLiveLong** [comment]
Thank you for your recognition of our work!
We are uploading the remaining sequences and it is expected to be done before May 8, 2022 except for one or two sequences that are related to sensitive information.
In addition, Baidu Netdisk is quite a convenient tool and we hope it will be helpful.

**Comment by SleepEarlyLiveLong** [comment]
All sequences of the WHUVID have been uploaded.
