### ISSUE TITLE
zip files to enable convenient download

### ISSUE THREAD

**Issue by Darren-Price** [chentianyangWHU/WHUVID#2]
Fantastic source of data for the research community, but access could be more convenient.

Would it be possible to upload cam0 and cam1 sequences packaged as zip files? This would enable more convenient download when using Motrix or equivalent download manager for those without Baidu account.

**Comment by SleepEarlyLiveLong** [comment]
Thank you for your advice.
Files of sequence 002-034 were uploaded as zip files. You can download them first.
Files of sequence 001 will be packaged as zip files and uploaded within 12 hours.
