### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by aa-samad** [chentianyangWHU/WHUVID#4]
The baidu links provided is looped and never reaches download!
Please help! I am accessing them from the Netherlands.

**Comment by SleepEarlyLiveLong** [comment]
My bad to forgot updatethe link cause I'm so busy these days.

I promise to deal this issue before this Saturday(2022/11/12).


Sincere apology!

**Comment by aa-samad** [comment]
Problem resolved!
I had issue with downloading them on linux, did it on windows with creating Baidu account.

It's a very nice dataset. Thanks a lot for gathering it. 
However, the download speed is very low (100KB/s), if possible, please upload them somewhere else or provide a proxy to download it faster in Europe.

Thanks in advance.
