### ISSUE TITLE
VINS-mono config file

### ISSUE THREAD

**Issue by aa-samad** [chentianyangWHU/WHUVID#5]
Thank you for providing this great dataset.
Could you please share the config file of your VINS-mono code for your dataset so that we can reproduce the results you have and include the plots in our paper?

Appreciate the help in advance :)

**Comment by SleepEarlyLiveLong** [comment]
I'm sorry for the late reply.
The config file we used for VINS-Mono is the monocular-IMU configuration file. You can find it here:

<img width="441" alt="image" src="https://github.com/SleepEarlyLiveLong/WHUVID/assets/39194717/52aa44c6-123b-4374-b536-8e94fc607571">
