### ISSUE TITLE
VINS_FUSION problem

### ISSUE THREAD

**Issue by Charlesguo11** [chentianyangWHU/WHUVID#6]
I want to apply VINS_FUSION to this dataset, however, I do not know the config file like "euroc_stereo_imu_config.yaml". And I'm trying to run this dataset in the form of rosbag. So may I know if you are using rosbag? And could you please share it?
If not, how to organize a yaml file like euroc? Or is there any other way to calibrate the camera and IMU?
Thank you.

**Comment by Charlesguo11** [comment]
I successfully build my own yaml for further study, and I share my config here:

%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/imu0"
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"
output_path: "/home/gcl/catkin_ws/src/VINS-Fusion/vins_estimator/launch/"

cam0_calib: "cam0_zed.yaml"
cam1_calib: "cam1_zed.yaml"
image_width: 640
image_height: 360
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
#    data: [0.008151865817142985, 0.9996605296342409, -0.024746162835626976, 0.022009642363225456,
#         0.9999404077919916, -0.007969450652357784, 0.007461147437525375, -0.0018523410930785084,
#         0.00726140127552204, -0.0248055104298965, -0.9996659235483758, -0.023070561867408388,
#         0.0, 0.0, 0.0, 1.0]
   data:  [ 0.00815187, 0.99994041 , 0.0072614, 0.00184033,
         0.99966053 ,-0.00796945, -0.02480551, -0.02258921,
        -0.02474616,  0.00746115, -0.99966593 ,-0.02250438,
         0.0,          0.0,          0.0,          1.0]


body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
#    data: [0.008533979229391139, 0.9997126013742517, -0.022402809021162012, -0.0980164771144062,
#         0.999860259061585, -0.0082088973512261, 0.014562841535120956, -0.0018998775811275652,
#         0.014374753834842933, -0.022523957418787904, -0.999642955156682, -0.02095925250897706,
#         0.0, 0.0, 0.0, 1.0]
   data: [ 0.00853398,  0.99986026 , 0.01437475 , 0.00303737,
         0.9997126,  -0.0082089,  -0.02252396,  0.09750063,
        -0.02240281,  0.01456284, -0.99964296, -0.02311995,
         0.0,          0.0,          0.0,          1.0]


#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0

**Comment by Charlesguo11** [comment]
%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/imu0"
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"
output_path: "/home/gcl/catkin_ws/src/VINS-Fusion/vins_estimator/launch/"

cam0_calib: "cam0_zed.yaml"
cam1_calib: "cam1_zed.yaml"
image_width: 640
image_height: 360
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
#    data: [0.008151865817142985, 0.9996605296342409, -0.024746162835626976, 0.022009642363225456,
#         0.9999404077919916, -0.007969450652357784, 0.007461147437525375, -0.0018523410930785084,
#         0.00726140127552204, -0.0248055104298965, -0.9996659235483758, -0.023070561867408388,
#         0.0, 0.0, 0.0, 1.0]
   data:  [ 0.00815187, 0.99994041 , 0.0072614, 0.00184033,
         0.99966053 ,-0.00796945, -0.02480551, -0.02258921,
        -0.02474616,  0.00746115, -0.99966593 ,-0.02250438,
         0.0,          0.0,          0.0,          1.0]


body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
#    data: [0.008533979229391139, 0.9997126013742517, -0.022402809021162012, -0.0980164771144062,
#         0.999860259061585, -0.0082088973512261, 0.014562841535120956, -0.0018998775811275652,
#         0.014374753834842933, -0.022523957418787904, -0.999642955156682, -0.02095925250897706,
#         0.0, 0.0, 0.0, 1.0]
   data: [ 0.00853398,  0.99986026 , 0.01437475 , 0.00303737,
         0.9997126,  -0.0082089,  -0.02252396,  0.09750063,
        -0.02240281,  0.01456284, -0.99964296, -0.02311995,
         0.0,          0.0,          0.0,          1.0]


#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0

**Comment by Charlesguo11** [comment]
[summary.txt](https://github.com/SleepEarlyLiveLong/WHUVID/files/14000730/summary.txt)

**Comment by Charlesguo11** [comment]
I successfully build my yaml and I share it in the summary.txt file

**Comment by ZhengzheXu** [comment]
@Charlesguo11 Hi! I'm also working on this dataset with VINS-Fusion. I've converted the raw data into a ROS bag, but when I run the stereo-inertial version of VINS-Fusion, the odometry doesn't work correctly and the trajectories diverge. However, when I use only stereo without IMU, the localization works fine. Do you happen to know what might be causing this?

**Comment by JimmyLzx** [comment]
@ZhengzheXu Hi! Have you figured out this problem? I've also encountered this one as well. It's so tricky.
